// Thumb Combos
#define COMBO_COUNT 8
#define COMBO_TERM 200
#define EXTRA_SHORT_COMBOS
#define TAPPING_TERM 180
#define TAPPING_TERM_PER_KEY

#define IGNORE_MOD_TAP_INTERRUPT
#define QUICK_TAP_TERM 0
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

